services:
  ingress:
    image: nginx:alpine
    ports:
      - "3000:3000"
    configs:
      - source: nginx_conf
        target: /etc/nginx/nginx.conf
    networks:
      - app
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.ingress == true
      restart_policy:
        condition: any
        delay: 1s
  nextjs:
    image: next-nest/nextjs:latest
    build:
      context: .
      dockerfile: apps/nextjs/Dockerfile
    environment:
      - PORT=3000
      - HOSTNAME=0.0.0.0
      - NEST_INTERNAL_URL=http://nestjs:3001
      - HOST_MACHINE_NAME={{.Node.Hostname}}
    networks:
      - app
    depends_on:
      - nestjs
    deploy:
      replicas: 3
      update_config:
        parallelism: 1
        delay: 1s
        order: start-first
      rollback_config:
        parallelism: 1
        order: stop-first
      restart_policy:
        condition: any
        delay: 2s
        max_attempts: 0
  nestjs:
    image: next-nest/nestjs:latest
    build:
      context: .
      dockerfile: apps/nestjs/Dockerfile
    environment:
      - PORT=3001
      - HOST_MACHINE_NAME={{.Node.Hostname}}
    networks:
      - app
    deploy:
      replicas: 3
      update_config:
        parallelism: 1
        delay: 1s
        order: start-first
      rollback_config:
        parallelism: 1
        order: stop-first
      restart_policy:
        condition: any
        delay: 2s
        max_attempts: 0

configs:
  nginx_conf:
    file: ./nginx.conf

networks:
  app:
    driver: overlay
    # https://docs.docker.com/engine/network/drivers/overlay/
    # This enables IPsec encryption at the level of the Virtual Extensible LAN (VXLAN).
    # This encryption imposes a non-negligible performance penalty, so you should test this option before using it in production.
    # driver_opts:
    #   encrypted: "true"
